// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAum306ugtudQMWgi0kEok0YLJ9-9etDV8',
    appId: '1:367301688722:web:445bdc3c0a3b6329f6554b',
    messagingSenderId: '367301688722',
    projectId: 'elma-88729',
    authDomain: 'elma-88729.firebaseapp.com',
    storageBucket: 'elma-88729.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgvYjM5x6AA96nsXM0iWHd3bw51WHs6f8',
    appId: '1:367301688722:android:8378b053262bd585f6554b',
    messagingSenderId: '367301688722',
    projectId: 'elma-88729',
    storageBucket: 'elma-88729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYYVEh1DgeP2bPSw90cm2YifoVft6CoAs',
    appId: '1:367301688722:ios:fc235cedf520eea3f6554b',
    messagingSenderId: '367301688722',
    projectId: 'elma-88729',
    storageBucket: 'elma-88729.firebasestorage.app',
    iosBundleId: 'com.example.elma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYYVEh1DgeP2bPSw90cm2YifoVft6CoAs',
    appId: '1:367301688722:ios:fc235cedf520eea3f6554b',
    messagingSenderId: '367301688722',
    projectId: 'elma-88729',
    storageBucket: 'elma-88729.firebasestorage.app',
    iosBundleId: 'com.example.elma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAum306ugtudQMWgi0kEok0YLJ9-9etDV8',
    appId: '1:367301688722:web:85cdf079ea6624c7f6554b',
    messagingSenderId: '367301688722',
    projectId: 'elma-88729',
    authDomain: 'elma-88729.firebaseapp.com',
    storageBucket: 'elma-88729.firebasestorage.app',
  );
}
